services:
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8787:8787"
    environment:
      # 透過環境變數注入，優於寫死在程式碼
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=${ORACLE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${ORACLE_PASSWORD}
    networks:
      - backend-net
    depends_on:
      oracle-db:
        condition: service_healthy # 關鍵：DB 健康才啟動 App
      alloy:
        condition: service_started
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      # Oracle DB 的環境變數設定，根據官方文件，這些是必要的參數
      # Oracle 的啟動腳本（runOracle.sh）內部有一套預設的命名規則（預設 SID 就是 FREE，PDB 就是 FREEPDB1）。
      - ORACLE_SID=FREE
      - ORACLE_PDB=FREEPDB1
      - ORACLE_USERNAME=${ORACLE_USERNAME}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata
      # 存放啟動腳本
      - ./init-scripts:/opt/oracle/scripts/startup
      # 存放範本檔案 (掛載到另一個自定義目錄)
      - ./init-scripts-template:/opt/oracle/template
    healthcheck:
      # 透過 sqlplus 檢查 PDB 是否已經 Ready
      test: [ "CMD-SHELL", "sqlplus -L ${ORACLE_USERNAME}/${ORACLE_PASSWORD}@FREEPDB1 <<<'exit;'" ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 90s
    networks:
      - backend-net

  # 使用 Grafana Alloy (現代化的收集器，取代舊的 Prometheus Agent)
  alloy:
    image: grafana/alloy:latest
    # 將當前目錄掛載到容器內的 /etc/alloy，讓 Alloy 可以讀取配置文件
    volumes:
      - ./:/etc/alloy/
    # 運行 Alloy，指定存儲路徑和配置文件位置
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "4318:4318" # 接收 OTLP 資料的端口
    # 確保 Alloy 在 Prometheus 啟動後才啟動，因為 Alloy 需要將資料發送到 Prometheus
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    # 將當前目錄掛載到容器內的 /etc/prometheus，讓 Prometheus 可以讀取配置文件
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # 運行 Prometheus，指定配置文件位置，並開啟接收功能以接收 Grafana Alloy 發送的資料
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=remote-write-receiver
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    # 允許匿名訪問 Grafana，並將匿名用戶設置為 Admin 角色，以便在 Grafana 中查看和管理數據
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
networks:
  # 區分網路：app 只需要把資料推給 alloy，不需要直接接觸 prometheus
  backend-net:
    driver: bridge
  # 監控工具之間的內部通訊
  monitor-net:
    driver: bridge

volumes:
  # 命名磁碟卷：確保你壓測完重啟容器，數據（圖表、指標）不會消失
  alloy-data:
  prometheus-data:
  grafana-data:
  oracle-data:
