spring.application.name=demo
spring.main.web-application-type=servlet
server.port=8087
# Oracle Database Connection Settings (from jpa project)
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=${ORACLE_USERNAME}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# HikariCP Connection Pool Settings
# Connection timeout in milliseconds
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=100

logging.level.com.example.demo=INFO

# Hibernate DDL Auto Configuration (from jpa project), none, update, create, create-drop
spring.jpa.hibernate.ddl-auto=create-drop

# Enable virtual threads for better concurrency (requires Java 19+)
spring.threads.virtual.enabled=true

# Expose specific Actuator endpoints for health, info, and metrics
management.endpoints.web.exposure.include=health,info,metrics

# Base URL for external services
app.base-url=http://localhost:${server.port}

# HTTP Client Connection Pool and Timeout Settings
#milliseconds
http.client.max-total=2000
http.client.default-max-per-route=1500
#seconds
http.client.connection-request-timeout=4
http.client.response-timeout=6
http.client.evict-idle-connections-period=30