spring:
  datasource:
    url: jdbc:oracle:thin:@//oracle-db:1521/FREEPDB1
    username: ${ORACLE_DEV_USERNAME}
    password: ${ORACLE_DEV_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create-drop  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true  # 開發環境顯示 SQL 語句，方便除錯
  flyway:
    enabled: false  # 不使用 Flyway，使用 JPA DDL auto

logging:
  level:
    com.ibm.demo: DEBUG

management:
  otlp:
    metrics:
      export:
        url: http://alloy:4318/v1/metrics
        enabled: true
        step: 10s
  metrics:
    tags:
      application: ${spring.application.name}
